dataset:
  repo_id: repo_pi05
  root: /data/datasets/datasets-hf/dataset_challenge_merged/four_types_merged

policy:
  type: pi05
  device: cuda
  push_to_hub: false
  pretrained_path: /home/wzb/challenges/lehome-challenge/outputs/train/pi05_merged/checkpoints/last/pretrained_model
  chunk_size: 10
  n_action_steps: 10
  dtype: bfloat16
  optimizer_lr: 2e-5
  scheduler_decay_lr: 1e-5
  scheduler_warmup_steps: 1000
  scheduler_decay_steps: 30000

  input_features:
    observation.state:
      type: STATE
      shape: [12]
    observation.images.top_rgb:
      type: VISUAL
      shape: [3, 480, 640]
    observation.images.left_rgb:
      type: VISUAL
      shape: [3, 480, 640]
    observation.images.right_rgb:
      type: VISUAL
      shape: [3, 480, 640]

  output_features:
    action:
      type: ACTION
      shape: [12]

output_dir: outputs/train/pi05_merged_fine
batch_size: 16
steps: 30000
save_freq: 10000
log_freq: 1000

wandb:
  # enable: false
  enable: true
  project: pi05_folder