dataset:
  repo_id: top_long_pant_short
  root: /data/datasets/datasets-hf/dataset_challenge_merged/pant_short_merged_extra

policy:
  type: pi05
  device: cuda
  push_to_hub: false
  pretrained_path: /home/wzb/challenges/lehome-challenge/outputs/train/pi05_extra_pantshort/checkpoints/006000/pretrained_model
  chunk_size: 20
  n_action_steps: 10
  dtype: bfloat16
  optimizer_lr: 4e-5
  scheduler_decay_lr: 2e-5
  scheduler_warmup_steps: 3000
  scheduler_decay_steps: 12000
  gradient_checkpointing: true
  normalization_mapping:
    VISUAL: IDENTITY
    STATE: MEAN_STD
    ACTION: MEAN_STD

  input_features:
    observation.state:
      type: STATE
      shape: [12]
    observation.images.top_rgb:
      type: VISUAL
      shape: [3, 480, 640]
    observation.images.left_rgb:
      type: VISUAL
      shape: [3, 480, 640]
    observation.images.right_rgb:
      type: VISUAL
      shape: [3, 480, 640]

  output_features:
    action:
      type: ACTION
      shape: [12]

output_dir: outputs/train/pi05_extra_pantshort_new
batch_size: 64
steps: 12000
save_freq: 3000
log_freq: 500

wandb:
  enable: true
  project: pi05_folder_pant_short
