dataset:
  repo_id: topshort
  root: /data/datasets/datasets-hf/dataset_challenge_merged/top_short_merged

policy:
  type: pi05
  device: cuda
  push_to_hub: false
  pretrained_path: /home/wzb/challenges/lehome-challenge/outputs/train/top_short_pi05_continue/checkpoints/006000/pretrained_model
  chunk_size: 50
  n_action_steps: 10
  dtype: bfloat16
  optimizer_lr: 3e-5
  scheduler_decay_lr: 1e-5
  scheduler_warmup_steps: 1000 #太多了，下次一步到位吧1000 或者2000
  scheduler_decay_steps: 30000
  gradient_checkpointing: true

  input_features:
    observation.state:
      type: STATE
      shape: [12]
    observation.images.top_rgb:
      type: VISUAL
      shape: [3, 480, 640]
    observation.images.left_rgb:
      type: VISUAL
      shape: [3, 480, 640]
    observation.images.right_rgb:
      type: VISUAL
      shape: [3, 480, 640]

  output_features:
    action:
      type: ACTION
      shape: [12]

output_dir: outputs/train/top_short_pi05_continue_full
batch_size: 32
steps: 30000
save_freq: 3000
log_freq: 500

wandb:
  enable: true
  project: pi05_top_short