dataset:
  repo_id: topshort
  root: /data/datasets/datasets-hf/dataset_challenge_merged/top_short_merged

policy:
  type: pi05_spatial_forcing
  device: cuda
  push_to_hub: false
  pretrained_path: /home/wzb/challenges/lehome-challenge/outputs/train/top_short_pi05/checkpoints/006000/pretrained_model #用的是top short用50训练的筛选过的
  chunk_size: 50
  n_action_steps: 10
  dtype: bfloat16
  optimizer_lr: 3e-5
  scheduler_decay_lr: 1e-5
  scheduler_warmup_steps: 1000
  scheduler_decay_steps: 30000
  gradient_checkpointing: true

  vla_layers_align: 12
  vggt_weight_path: /home/wzb/challenges/lehome-challenge/Spatial-Forcing/openpi-SF/checkpoints/vggt
  vggt_dim: 1024
  pooling_func: bilinear
  use_vggt_pe: false
  use_vlm_norm: false
  align_loss_coeff: 0.5 #这个是loss权重，原代码中pi0_align_aloha_place_block设置的是0.5

  input_features:
    observation.state:
      type: STATE
      shape: [12]
    observation.images.top_rgb:
      type: VISUAL
      shape: [3, 480, 640]
    observation.images.left_rgb:
      type: VISUAL
      shape: [3, 480, 640]
    observation.images.right_rgb:
      type: VISUAL
      shape: [3, 480, 640]

  output_features:
    action:
      type: ACTION
      shape: [12]

output_dir: outputs/train/top_short_pi05_spatial_forcing
batch_size: 32
steps: 30000
save_freq: 3000
log_freq: 500

wandb:
  enable: true
  project: pi05_top_short_spatial_forcing
